#
# Copyright © 2015 Thiago Moreira (tmoreira2020@gmail.com)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

architect:
- tmoreira2020
assets:
  pubring.gpg: tmoreira2020/home#assets/pubring.gpg
  secring.gpg: tmoreira2020/home#assets/secring.gpg
  settings.xml: tmoreira2020/home#assets/settings.xml
merge:
  script: |-
    mvn clean install --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
deploy:
  script: |-
    mvn clean deploy --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    sed "s/>[0-9].[0-9].[0-9]</>${tag}</g" README.md > README.md.releaseBackup
    cp README.md.releaseBackup README.md
    sed "s/\"[0-9].[0-9].[0-9]\"/\"${tag}\"/g" README.md > README.md.releaseBackup
    cp README.md.releaseBackup README.md
    git commit -am "${tag}"
    mvn clean deploy -Psonatype-oss-release --errors --settings ../settings.xml
    git checkout master
    git merge __rultor
    git checkout -b develop
    mvn build-helper:parse-version versions:set -DnewVersion=$\{parsedVersion.majorVersion\}.$\{parsedVersion.minorVersion\}.$\{parsedVersion.nextIncrementalVersion\}-SNAPSHOT
    git commit -am "Prepare for next development iteration"
    git checkout master
  commanders:
  - tmoreira2020
