architect:
- tmoreira2020
assets:
  pubring.gpg: tmoreira2020/home#assets/pubring.gpg
  secring.gpg: tmoreira2020/home#assets/secring.gpg
  settings.xml: tmoreira2020/home#assets/portal-properties-prettier-app/settings.xml
merge:
  script: |-
    mvn clean install --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
deploy:
  script: |-
    mvn clean deploy --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    sed "s/[0-9].[0-9].[0-9]/${tag}/g" README.md > README.md.releaseBackup
    cp README.md.releaseBackup README.md
    git commit -am "${tag}"
    mvn clean deploy -Pportal-properties-prettier-app --errors --settings ../settings.xml
  commanders:
  - tmoreira2020
